### ISSUE TITLE
I executed '''python3 tests/01_hello_world.py''' on mac and I got the following error.

### ISSUE THREAD

**Issue by xiaoqge** [tokenika/eosfactory#115]
I executed  `python3 tests/01_hello_world.py` on mac and I got the following error.

```
➜  eosfactory git:(master)  python3 tests/01_hello_world.py

###  SCENARIO:
Create a contract from template, then build and deploy it.

Removing testnet cache for prefix `_127_0_0_1_8888_`
Testnet cache successfully removed.
Local node is stopped [].
...............Local node is stopped [18832].
...............E
======================================================================
ERROR: setUpClass (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/li.yun/Documents/Blockchain/eosfactory/eosfactory/core/manager.py", line 130, in node_start
    teos.node_probe(verbosity)
  File "/Users/li.yun/Documents/Blockchain/eosfactory/eosfactory/core/teos.py", line 556, in node_probe
    ''')
eosfactory.core.errors.Error: ERROR:
The local node does not respond.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/01_hello_world.py", line 19, in setUpClass
    reset()
  File "/Users/li.yun/Documents/Blockchain/eosfactory/eosfactory/core/manager.py", line 149, in reset
    clear=True, nodeos_stdout=nodeos_stdout, verbosity=verbosity)
  File "/Users/li.yun/Documents/Blockchain/eosfactory/eosfactory/core/manager.py", line 133, in node_start
    teos.node_probe(verbosity)
  File "/Users/li.yun/Documents/Blockchain/eosfactory/eosfactory/core/teos.py", line 556, in node_probe
    ''')
eosfactory.core.errors.Error: ERROR:
The local node does not respond.

----------------------------------------------------------------------
Ran 0 tests in 31.494s

FAILED (errors=1)
```

**Comment by stefanzarembinski** [comment]
I guess that the nodeos executable is not satisfied with the command line send by EOSFactory. You can read the command line:

First, open the script `tests/01_hello_world.py` in an editor.
Replace the the line number `19`

    reset()

with the following three lines:

    setup.is_print_command_line = True
    reset()
    setup.is_print_command_line = False

Next, run the script: python3 tests/01_hello_world.py

You will see in the outputs something like this:

nodeos command line:
/usr/bin/nodeos --http-server-address 127.0.0.1:8888 --data-dir /mnt/c/Workspaces/EOS/eosfactory/localnode/ --config-dir /mnt/c/Workspaces/EOS/eosfactory/localnode/ --chain-state-db-size-mb 200 --contracts-console --verbose-http-errors --enable-stale-production --producer-name eosio --signature-provider EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV=KEY:5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 --plugin eosio::producer_plugin --plugin eosio::chain_api_plugin
--plugin eosio::http_plugin --plugin eosio::history_api_plugin --genesis-json /mnt/c/Workspaces/EOS/eosfactory/localnode/genesis.json --delete-all-blocks

Now, you can try te command line in a bash terminal:

$ /usr/bin/nodeos --http-server-address 127.0.0.1:8888 --data-dir /mnt/c/Workspaces/EOS/eosfactory/localnode/ --config-dir /mnt/c/Workspaces/EOS/eosfactory/localnode/ --chain-state-db-size-mb 200 --contracts-console --verbose-http-errors --enable-stale-production --producer-name eosio --signature-provider EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV=KEY:5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 --plugin eosio::producer_plugin --plugin eosio::chain_api_plugin
--plugin eosio::http_plugin --plugin eosio::history_api_plugin --genesis-json /mnt/c/Workspaces/EOS/eosfactory/localnode/genesis.json --delete-all-blocks


The nodeos will print an error message. Please, send it to me.

Your feedback prompts me to address problems like yours one. In the next edition of EOSFactory, soon, the issue will be better manageable.

SZ

**Comment by xiaoqge** [comment]
Thank you,I will follow the instructions of yours and will continue to loop all the time. Below is the pop-up window of my MACOS
`/usr/local/bin/nodeos --http-server-address 127.0.0.1:8888 --data-dir /Users/li.yun/Documents/Blockchain/eosfactory/localnode/ --config-dir /Users/li.yun/Documents/Blockchain/eosfactory/localnode/ --chain-state-db-size-mb 200 --contracts-console --verbose-http-errors --enable-stale-production --producer-name eosio --signature-provider EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV=KEY:5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 --plugin eosio::producer_plugin --plugin eosio::chain_api_plugin --plugin eosio::http_plugin --plugin eosio::history_api_plugin --genesis-json /Users/li.yun/Documents/Blockchain/eosfactory/localnode/genesis.json --delete-all-blocks`

**Comment by xiaoqge** [comment]
The above error, I have already solved it.
Execute the command `brew uninstall --force gettext && brew install gettext`

But another error has occurred
`######### Created contract project ``_wslqwjvacdyugodewiyd``, originated from template ``/Users/li.yun/Documents/Blockchain/eosfactory/templates/contracts/01_hello_world``.
ELocal node is stopped [25147].

======================================================================
ERROR: test_01 (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/01_hello_world.py", line 44, in test_01
    contract.build()
  File "/Users/li.yun/Documents/Blockchain/eosfactory/eosfactory/shell/contract.py", line 46, in build
    self.build_abi()
  File "/Users/li.yun/Documents/Blockchain/eosfactory/eosfactory/shell/contract.py", line 42, in build_abi
    teos.ABI(self.contract_dir)
  File "/Users/li.yun/Documents/Blockchain/eosfactory/eosfactory/core/teos.py", line 102, in ABI
    config.eosio_abigen(),
  File "/Users/li.yun/Documents/Blockchain/eosfactory/eosfactory/core/config.py", line 134, in eosio_abigen
    return first_valid_path(eosio_abigen_)
  File "/Users/li.yun/Documents/Blockchain/eosfactory/eosfactory/core/config.py", line 294, in first_valid_path
    '''.format(config_list[0]))
eosfactory.core.errors.Error: ERROR:
Cannot find any path for 'EOSIO_ABIGEN'.

----------------------------------------------------------------------`

**Comment by stefanzarembinski** [comment]
Note that there is a new edition of EOSFactory on github: version 2.4. It is cleaned and much better documented. Please, switch to this version.

I guess, that the error, you report, is because do not have `eosio.cdt` installed. Please, see tutorial `Installing EOSFactory`.
There you can read:
    Also, we assume that you have installed eosio.cdt v1.41. Binary installation suffices.

**Comment by stefanzarembinski** [comment]
You write: `In addition, I am worried about security ...` 

I guess, you are surprizes seeing private keys. The exposition of the private keys is not issue of EOSFactory: it result from EOSIO design decisions. This design is that, in your own computer you have to feel safe.

Therefore, you can access your private keys that you keep in your local wallet.
However, EOSIO cleos never exports your private keys outside.

**Comment by stefanzarembinski** [comment]
Back to the `EOSIO_ABIGEN` issue.
Even if you have `eosio.cdt` installed, it may not include `eosio-abigen` executable as it is outdated.

The EOSFactory version 2.4 does not use this `eosio-abigen`. Please, change to 2.4.

**Comment by xiaoqge** [comment]
brew install eosio.cdt

**Comment by xiaoqge** [comment]
Thank you very much, the problem has been solved
