### ISSUE TITLE
EOS Factory fails to start nodeos-1.6.0 due to obsoluted option in config file.

### ISSUE THREAD

**Issue by rkintzi** [tokenika/eosfactory#129]
Config file used by EOS Factory to start nodeos contains `max-implicit-request` option, which was removed in nodeos 1.6.0. This makes EOS Factory incompatible with the newest version of nodeos.

**Comment by stefanzarembinski** [comment]
I see, you use the contribution from ED Easy-D (Pull request: "Fix unrecognised option 'max-implicit-request' error on startup").
We will include it to the next distribution of EOSFactory.

**Comment by rkintzi** [comment]
Fixed with #125
