### ISSUE TITLE
Should force unique be set by default?

### ISSUE THREAD

**Issue by drdgvhbh** [tokenika/eosfactory#139]
Wondering whats everyone's thoughts on the force unique flag being set on by default? Often times I find myself recreating the same account and pushing the same action in the `setup phase` but I run into this error when doing so

```sh
Error 3040008: Duplicate transaction
You can try embedding eosio nonce action inside your transaction to ensure uniqueness.
Error Details:
duplicate transaction accf37ffb1beeea853031c6ad8a74426cc4ca3f76604f95450eb60976fccab1d
```

Obviously this is fixed by adding the force unique flag to each push action call... however it would seem more convenient if it was on by default in the context of writing tests.

**Comment by stefanzarembinski** [comment]
I know this error: it happens bay it disappears in a subsequent execution of the same command. I believe that it proves an instability problem of the blockchain.

The blockchain features few instability problems. For example, is refuses restarting sometimes. EOSFactory meets this problem with sequential attempts. In the same way another instability is addressed. I plan to include the `Duplicate transaction` error to the same service.

**Comment by stefanzarembinski** [comment]
It is finished, I see. Closing.
