### ISSUE TITLE
Support of secondary index query?

### ISSUE THREAD

**Issue by Patrick-Shih** [tokenika/eosfactory#141]
Is eosfactory currently support query multi-index table with other than the primary key, i.e., by secondary index, or even the third?

In my test scenario I want to get the row using secondary index like
```
cleos get table account scope table --key-type i64 --index 2 -L 10 -U 10
```

It looks like there is no `index` parameter in the [table](https://github.com/tokenika/eosfactory/blob/master/eosfactory/shell/account.py#L305) method

So, is it currently supported? If yes, please let me know how to use it.

BTW, what is the `key` parameter used for in account.table method? I try to give it some value like '1', 'i32', '2' but it seems nothing is affected

**Comment by stefanzarembinski** [comment]
Thank you for the remark: the `account.table` needs updating.
I correct it. The corrected version will be published soon, today or tomorrow with a new edition of EOSFactory.
I you are in a hurry, updated version is in the branch `pypi-ready`.
