### ISSUE TITLE
Can't install eosfactory

### ISSUE THREAD

**Issue by thekevinbrown** [tokenika/eosfactory#145]
Trying to install EOSFactory results in this in the output:

```
Configuring the eosfactory installation...

Traceback (most recent call last):
  File "eosfactory/install.py", line 18, in <module>
    install()
  File "eosfactory/install.py", line 13, in install
    config.set_contract_workspace_dir()
AttributeError: module 'eosfactory.core.config' has no attribute 'set_contract_workspace_dir'
NOTE!
The version of the installed 'eosio' package is 1.6.2 while the expected
version is 1.6.0
```

Then when I try to run `python3 tests/hello_world.py` to see if it worked, I get this:

```
$ python3 tests/hello_world.py
NameError: name 'MasterAccount' is not defined
```

Especially since `brew` won't let you install old versions, it'd be great if it could be a bit more forgiving on its versions that it works with. How should I get this installed?

**Comment by stefanzarembinski** [comment]
The version difference is not a problem here: EOSFactory just notes the fact. Please, try the newest version v3.0.2.

**Comment by thekevinbrown** [comment]
This was with version 3.0.2.

Even if I worked through this, I now realise I'd be blocked on #149, so I'll go ahead and close this because there's not much point in working through it until the tool works with multiple contracts.

**Comment by stefanzarembinski** [comment]
Please, do
```
 python3 -m eosfactory.config
```
Let me know the result.
