### ISSUE TITLE
changing http-server-address 

### ISSUE THREAD

**Issue by arslankhalidch** [tokenika/eosfactory#164]
Hi, I am trying to set up https://github.com/playerone-id/EosCommander. I am new to coding and blockchain but following the tutorial on EOSCommander. It says I need to have a different http-server-address instead of the default 127.0.0.1:8999.

Can anyone help?

**Comment by stefanzarembinski** [comment]
Here, we develop EOSFactory. I see that you cannot expect any help to your question here. Therefore, I close the issue.
