### ISSUE TITLE
Build Error - Dawn 4.1

### ISSUE THREAD

**Issue by cipherzzz** [tokenika/eosfactory#20]
Hey guys, I'm excited to use this product - I get this when I ran the build script this weekend on my `dawn-v4.1.0` repo.

`./build.sh -e ../eos`

```
/Users/markmathis/Projects/EOS/eosfactory/teos_lib/eos_interface.cpp:11:10: fatal error: 
      'fc/variant.hpp' file not found
#include <fc/variant.hpp>
         ^~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/teoslib.dir/eos_interface.cpp.o] Error 1
make[1]: *** [CMakeFiles/teoslib.dir/all] Error 2
make: *** [all] Error 2

	
>>>>>> MAKE building teos_lib has exited with the above error.
```

I saw that you had another [issue](https://github.com/tokenika/eosfactory/issues/9) open similar to this one where you stated Dawn 4.1 would be supported soon?

**Comment by jakub-zarembinski** [comment]
Unfortunately, at this stage EOSFactory is NOT compatible with EOS Dawn 4.1.0.
We are working on it.

For the time being try to downgrade to `dawn-v4.0.0`:
```
cd eos
git checkout dawn-v4.0.0
git submodule update --init --recursive
./eosio_build.sh
```
