### ISSUE TITLE
Not work:   python3 ./pyteos/eosf.py contract.name skeleton

### ISSUE THREAD

**Issue by trungtt1981** [tokenika/eosfactory#27]
I've followed the tutorial [http://eosfactory.io/sphinx/build/html/tutorials/04.WorkingWithEOSContractsUsingEOSFactoryInVSC.html](url). 
However, I cannot generate a workspace for new smart contract because the following cmd doesn't work out
`python3 ./pyteos/eosf.py contract.name skeleton`

I stick to use nodeos of dawn-4.0 and the eosfactory is at this commit
`3b3f8dcd521260faa58743fc284cfb970ee722ad`

Another question is where the new workspace is created?

**Comment by jakub-zarembinski** [comment]
The new version is out.
Please check out the `master` branch.
