### ISSUE TITLE
test1.py failed...

### ISSUE THREAD

**Issue by hwnahm** [tokenika/eosfactory#3]
peter:eosfactory peter$ python3 --version
Python 3.6.5
peter:eosfactory peter$ 

peter:eosfactory peter$ python3 ./tests/test1.py 
Reading setup from file:
   /Users/peter/devel/eosfactory/config.json
Version: 0.8.2
test node.reset():
Traceback (most recent call last):
  File "./tests/test1.py", line 69, in <module>
    run()
  File "./tests/test1.py", line 9, in run
    node.reset()
  File "/Users/peter/devel/eosfactory/pyteos/node.py", line 20, in reset
    pyteos.node_reset()
  File "/Users/peter/devel/eosfactory/pyteos/pyteos.py", line 1041, in node_reset
    _StartNode(1, True)
  File "/Users/peter/devel/eosfactory/pyteos/pyteos.py", line 694, in __init__
    self.command_line = self.json["command_line"]
TypeError: string indices must be integers
peter:eosfactory peter$

**Comment by jakub-zarembinski** [comment]
Looks like EOSFactory failed to launch your nodeos daemon.

To verify can you navigate to {Path to your EOSIO code}/build/programs/nodeos/ and then run this command in your terminal:
./nodeos --genesis-json /Users/peter/devel/eosfactory/build/daemon/data-dir/genesis.json --http-server-address 127.0.0.1:8888 --data-dir /Users/peter/devel/eosfactory/build/daemon/data-dir --config-dir /Users/peter/devel/eosfactory/build/daemon/data-dir --wallet-dir /Users/peter/devel/eosfactory/build/daemon/data-dir/wallet --shared-memory-size-mb 100 --resync-blockchain

Also, what OS are you running?
And are you sure you have EOS `dawn-v4.0.0` installed?

**Comment by hwnahm** [comment]
I am using macOS High Sierra (version 10.13.4)
and also I installed EOS from git master.

Thanks

2018-05-15 17:51 GMT+09:00 jakub-zarembinski <notifications@github.com>:

**Comment by jakub-zarembinski** [comment]
And did the command run successfully?

**Comment by hwnahm** [comment]
Yes. It works properly.

I am running it right now to configure a BP.


2018-05-15 18:06 GMT+09:00 jakub-zarembinski <notifications@github.com>:

**Comment by hwnahm** [comment]
It is solved after kill my nodeos daemon.
Sorry about bugging you.
Thanks a lot.

2018-05-15 19:06 GMT+09:00 남현우 <hwnahm@gmail.com>:
