### ISSUE TITLE
How to set custom permissions with eosfactory?

### ISSUE THREAD

**Issue by basarrcan** [tokenika/eosfactory#34]
I am building unit tests for my contracts but some of my contracts invoke actions from other contracts so I need to set custom permissions in my scripts. Checked the documentation but couldn't find it. Is there any set permission functionality?

**Comment by andresberrios** [comment]
If there isn't (yet) you can simply call the `updateauth` action of the system contract (`eosio`). Check its ABI to know the exact parameters.

**Comment by jakub-zarembinski** [comment]
Taken from the latest `v2.0` release, here are some examples from the `02_eosio_token` demo contract:

* If you just need one account's permission:
```
host.push_action(
            "transfer",
            {
                "from": carol, "to": bob, 
                "quantity": "11.0000 EOS", "memo": ""
            },
            permission=(carol, Permission.ACTIVE))
```
* If you need multiple accounts' permission:
```
host.push_action(
            "create",
            {
                "issuer": master,
                "maximum_supply": "1000000000.0000 EOS",
                "can_freeze": "0",
                "can_recall": "0",
                "can_whitelist": "0"
            },
            permission=[(master, Permission.OWNER), (host, Permission.ACTIVE)])
```

The file is located here:
https://github.com/tokenika/eosfactory/blob/dev/contracts/02_eosio_token/test/unittest1.py
(I'm pointing you to the `dev` branch, as there the examples are more explicit.)

**Comment by golovin** [comment]
> Taken from the latest `v2.0` release, here are some examples from the `02_eosio_token` demo contract:
> 
>     * If you just need one account's permission:
> 
> 
> ```
> host.push_action(
>             "transfer",
>             {
>                 "from": carol, "to": bob, 
>                 "quantity": "11.0000 EOS", "memo": ""
>             },
>             permission=(carol, Permission.ACTIVE))
> ```
> 
>     * If you need multiple accounts' permission:
> 
> 
> ```
> host.push_action(
>             "create",
>             {
>                 "issuer": master,
>                 "maximum_supply": "1000000000.0000 EOS",
>                 "can_freeze": "0",
>                 "can_recall": "0",
>                 "can_whitelist": "0"
>             },
>             permission=[(master, Permission.OWNER), (host, Permission.ACTIVE)])
> ```
> 
> The file is located here:
> https://github.com/tokenika/eosfactory/blob/dev/contracts/02_eosio_token/test/unittest1.py
> (I'm pointing you to the `dev` branch, as there the examples are more explicit.)

This is not the author asking for...

In case when contract B should call method from contract A (eosio.token) on behalf of active user we have to set eosio.code permission. Manually it can be done by this command
`cleos set account permission user1 active '{"threshold": 1,"keys": [{"key": "PRIVATE_KEY","weight": 1}],"accounts": [{"permission":{"actor":"contractB","permission":"eosio.code"},"weight":1}]}' owner -p user1`

How it can be done via eosfactory?

**Comment by jakub-zarembinski** [comment]
You are right, EOS Factory is missing an important feature.
We'll aim to cover it in the next release.

**Comment by alexgonz** [comment]
> You are right, EOS Factory is missing an important feature.
> We'll aim to cover it in the next release.

Are there any updates regarding this?

**Comment by jakub-zarembinski** [comment]
Hi,
Permissions should be working in the current release.
Please refer to these docs:
http://eosfactory.io/build/html/patterns/set/set_account_permission.html
http://eosfactory.io/build/html/patterns/set/set_action_permission.html
