### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by delneg** [tokenika/eosfactory#4]
Hello guys, great work here
Just wanted to mention that some insight on current development status could be helpful - e.g. roadmap on new features, already implemented features, changelog and/or compatibilty with eos version, maybe list of some known-to-work as well as not implemented yet stuff

**Comment by jakub-zarembinski** [comment]
You're absolutely right, we definitely need to add this kind of document.

For the time being, here is a quick draft:
https://github.com/tokenika/eosfactory/blob/master/docs/sphinx/source/05.DevelopmentStatus.md

**Comment by jakub-zarembinski** [comment]
Release notes added to the official documentation:
http://eosfactory.io/sphinx/build/html/releases/ReleaseNotesVersion0.8.html

**Comment by delneg** [comment]
Thanks, that'll help a lot

**Comment by jakub-zarembinski** [comment]
The plan for a subsequent release:
https://github.com/tokenika/eosfactory/blob/master/docs/sphinx/source/roadmap/PlanForSubsequentEOSFactoryReleases.md

And a long-term vision:
https://github.com/tokenika/eosfactory/blob/master/docs/sphinx/source/roadmap/LongTermEOSFactoryRoadmap.md
