### ISSUE TITLE
Running node in background

### ISSUE THREAD

**Issue by ephdtrg** [tokenika/eosfactory#43]
I want to use eosfactory on server without actual screen (through SSH, etc), but for now, running tests explicitly needs to open gnome terminal for running node. Is it possible to run node in background, like how it does ethereum truffle and ganache?

**Comment by cthacker** [comment]
I'm going to 2nd this. If people can't run this remote it will be sparingly used.

**Comment by jakub-zarembinski** [comment]
> Is it possible to run node in background, like how it does ethereum truffle and ganache?

We've tried that but we couldn't find a satisfying solution that works across all platforms.

We will take another look at this problem and will let you know. Maybe we'll a offer GUI-less nodeos only for Linux-based OS.

**Comment by stefanzarembinski** [comment]
Fixed in the current edition.
