### ISSUE TITLE
how can I interact with public test net?

### ISSUE THREAD

**Issue by readygo586** [tokenika/eosfactory#45]
I hope to interact with public test net as following instruction mentioned, but can not find the ### **utils** folder.
Do I miss something?

![image](https://user-images.githubusercontent.com/41469645/45415324-fd4cc900-b6af-11e8-9b4d-68e533943085.png)

**Comment by jakub-zarembinski** [comment]
It's here:
https://github.com/tokenika/eosfactory/tree/master/utils
