### ISSUE TITLE
 fatal error: 'eosiolib/eosio.hpp' file not found

### ISSUE THREAD

**Issue by ricktobacco** [tokenika/eosfactory#47]
This occurs when I attempt  python3 tests/01_hello_world.py 

The output of my 
 eval $eosf get config
is
  {
      "EOSIO_SOURCE_DIR": "../eos",
      "EOSIO_EOSFACTORY_DIR": "/home/ricardo/Documents/eosfactory",
      "EOSIO_DATA_DIR": "/home/ricardo/Documents/eosfactory/build/daemon/data-dir/",
      "EOSIO_CONFIG_DIR": "/home/ricardo/Documents/eosfactory/build/daemon/data-dir/",
      "KEOSD_WALLET_DIR": "${HOME}/eosio-wallet/",
      "nodeExe": "../eos/build/programs/nodeos/nodeos",
      "cleosExe": "../eos/build/programs/cleos/cleos",
      "genesisJson": "/home/ricardo/Documents/eosfactory/build/daemon/data-dir/genesis.json",
      "EOSIO_DAEMON_ADDRESS": "127.0.0.1:8888",
      "EOSIO_KEY_PRIVATE":"5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3",
      "EOSIO_KEY_PUBLIC":"EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
      "EOSIO_WALLET_ADDRESS": "127.0.0.1:8888",
      "EOSIO_DAEMON_NAME": "nodeos",
      "EOSIO_WASM_CLANG": "/home/ricardo/opt/wasm/bin/clang",
      "EOSIO_BOOST_INCLUDE_DIR": "/home/ricardo/opt/boost/include",
      "EOSIO_WASM_LLVM_LINK": "/home/ricardo/opt/wasm/bin/llvm-link",
      "EOSIO_WASM_LLC": "/home/ricardo/opt/wasm/bin/llc",
      "EOSIO_S2WASM": "/usr/local/bin/eosio-s2wasm",
      "EOSIO_WAST2WASM": "/usr/local/bin/eosio-wast2wasm",
      "sharedMemory": "200",
      "contractWorkspace": "/home/ricardo/Documents/contracts/",
      "workspaceEosio": "../eos/build/contracts/"
 }

**Comment by jakub-zarembinski** [comment]
Hi, have you installed EOSIO after building it?

If not, you need to do it like this:
```
sudo ./eosio_install.sh
```

Please let me know if it helped.

**Comment by ricktobacco** [comment]
Yes I have done that.

**Comment by jakub-zarembinski** [comment]
Mine looks like this:
```
#  {
#      "EOSIO_SOURCE_DIR": "/mnt/x/Workspaces/EOS/eos",
#      "EOSIO_EOSFACTORY_DIR": "/mnt/x/Workspaces/EOS/eosfactory",
#      "EOSIO_DATA_DIR": "/mnt/x/Workspaces/EOS/eosfactory/build/daemon/data-dir/",
#      "EOSIO_CONFIG_DIR": "/mnt/x/Workspaces/EOS/eosfactory/build/daemon/data-dir/",
#      "KEOSD_WALLET_DIR": "${HOME}/eosio-wallet/",
#      "nodeExe": "/mnt/x/Workspaces/EOS/eos/build/programs/nodeos/nodeos",
#      "cleosExe": "/mnt/x/Workspaces/EOS/eos/build/programs/cleos/cleos",
#      "genesisJson": "/mnt/x/Workspaces/EOS/eosfactory/build/daemon/data-dir/genesis.json",
#      "EOSIO_DAEMON_ADDRESS": "127.0.0.1:8888",
#      "EOSIO_KEY_PRIVATE": "5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3",
#      "EOSIO_KEY_PUBLIC": "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
#      "EOSIO_WALLET_ADDRESS": "127.0.0.1:8888",
#      "EOSIO_DAEMON_NAME": "nodeos",
#      "EOSIO_WASM_CLANG": "/home/sygnet/opt/wasm/bin/clang",
#      "EOSIO_BOOST_INCLUDE_DIR": "/home/sygnet/opt/boost/include",
#      "EOSIO_WASM_LLVM_LINK": "/home/sygnet/opt/wasm/bin/llvm-link",
#      "EOSIO_WASM_LLC": "/home/sygnet/opt/wasm/bin/llc",
#      "EOSIO_S2WASM": "/usr/local/bin/eosio-s2wasm",
#      "EOSIO_WAST2WASM": "/usr/local/bin/eosio-wast2wasm",
#      "sharedMemory": "200",
#      "contractWorkspace": "/mnt/x/Workspaces/EOS/contracts",
#      "workspaceEosio": "/mnt/x/Workspaces/EOS/eos/build/contracts/"
#  }
```
Some of your paths seem to relative, instead of absolute, e.g.
```
"EOSIO_SOURCE_DIR": "../eos",
"nodeExe": "../eos/build/programs/nodeos/nodeos",
"cleosExe": "../eos/build/programs/cleos/cleos",
```
Please let me know the content of your `~/.profile` file (the bottom part where EOSFactory paths are defined, run `nano ~/.profile`),

Mine looks like this:
```
export EOSIO_SOURCE_DIR=/mnt/x/Workspaces/EOS/eos
export EOSIO_EOSFACTORY_DIR=/mnt/x/Workspaces/EOS/eosfactory
export U_HOME=/home/sygnet
export eosf=/mnt/x/Workspaces/EOS/eosfactory/teos/build/teos/teos
export EOSIO_CONTRACT_WORKSPACE=/mnt/x/Workspaces/EOS/contracts
export PYTHONPATH=/mnt/x/Workspaces/EOS/eosfactory/pyteos:/mnt/x/Workspaces/EOS/eosfactory/tests:
```

If you have relative paths there, try to remove all those export statements and reinstall EOSFactory by running:
```
./build.sh -e /mnt/d/Workspaces/EOS/eos -w /mnt/d/Workspaces/EOS/contracts
```
Of course change the paths to fit your configuration and make sure to use *absolute* paths. I'm assuming here that your problems are caused by using relative paths during EOSFactory installation.

When EOSFactory is reinstalled make sure to run `source ~/.profile` (or `source ~/.bash_profile` if you are on a MacOS).

Let me know if it helped.

**Comment by ricktobacco** [comment]
Thank you so much, yes the issue was the relative path I had for "nodeExe" and "cleosExe".
I should probably open a new issue for this, and I am sorry but I really need to figure out how to run on Jungle with EOSFactory. I saw there was a script for getting on CryptoKylin, are the steps very similar for getting on Jungle?

**Comment by ricktobacco** [comment]
Yes thank you, the issue was relative paths for the EOSIO env var.
I should probably open a separate issue for this, and I am sorry, but I really need to figure out how to run on Jungle with EOSFactory. I saw the test script for CryptoKylin, are the steps for running on Jungle similar?

**Comment by jakub-zarembinski** [comment]
To register an account on the Jungle testnet, you need to come up with an account name and and two public keys. EOSFactory gives you those, so that you can copy them into the [Create Account](http://dev.cryptolions.io/#account) form on the Jungle website.

Next, you need to fund the newly created account using the [Faucet](http://dev.cryptolions.io/#faucet) form on the Jungle website.

Next, switch back to EOSFactory, type `go` to finish the proces and let EOSFactory verify that the new account was successfully registered on the testnet.

Feel free to ask any further questions.

**Comment by ricktobacco** [comment]
Thank you so much for your feedback!
I have an action handler void getbalance(const char* symbol) and the first two things i do are 
require_auth(_self);
    symbol_name sym = string_to_symbol(4, symbol);
I am using the tests for token, so my first test in test1.py is 
account_host.push_action(
        "addbank",
        {
            "sym": "BTC",
        }, account_host)
I am getting a parse error for in the line number that says "account_host"
Failed with error: Parse Error (4)
Couldn't parse uint64_t

What could be the issue?

**Comment by ricktobacco** [comment]
Thank you so much for your feedback!
I have an action handler void getbalance(const char* symbol) and the first two things i do are
require_auth(_self);
symbol_name sym = string_to_symbol(4, symbol);
I am using the tests for token, so my first test in test1.py is
account_host.push_action(
"getbalance",
{
"sym": "BTC",
}, account_host)
I am getting a parse error for in the line number that says "account_host"
Failed with error: Parse Error (4)
Couldn't parse uint64_t

What could be the issue?

**Comment by ricktobacco** [comment]
Sometimes I get the errors "transaction took too long" and "deferred transaction with this payer and sender already exists". I understand why the second one is happening, although I don't think it should...but not the first one.
