### ISSUE TITLE
VSC does not recognize C++ includes

### ISSUE THREAD

**Issue by jakub-zarembinski** [tokenika/eosfactory#53]
I'm trying the `eosio_token` template. It builds fine, but in VSC it seems to think that some includes don't work:
```
#include <eosiolib/asset.hpp> is underlined and also
#include "eosio_token.hpp"
```

The error is:
```
cannot open source file "eosiolib/core_symbol.hpp" (dependency of...
```

**Comment by stefanzarembinski** [comment]
In the next edition, after 2.2, with eosio.cdt, the error disapiers. However, 
another one comes:
`cannot open source file "boost/limits.hpp"`

The missing dependency is not provided with the eosio.cdt -- what is an mistake,
evidently, as the other boost dependency is included. This condition is 
temporary as the all the boost is going to be removed from eosio.cdt.

In my computer:
$ locate boost/limits.hpp
/home/cartman/opt/boost/include/boost/limits.hpp
/home/cartman/opt/boost_1_66_0/include/boost/limits.hpp

Hence, if the missing intelisense is a problem, I can ad an entry to the file
`.vscode/c_cpp_properties.json
