### ISSUE TITLE
name 'run' is not defined

### ISSUE THREAD

**Issue by noisy** [tokenika/eosfactory#55]
In tutorial there is a section, when `run()` is used:

https://github.com/tokenika/eosfactory/blame/master/docs/tutorials/02.InteractingWithEOSContractsInEOSFactory.md#L51

but it looks like, there is not such method in `pyteos/eosf.py`. Have you had `resume()` in mind?

**Comment by jakub-zarembinski** [comment]
Yes, your're right. It will be fixed.

**Comment by noisy** [comment]
fixed in: https://github.com/tokenika/eosfactory/commit/1230406e9cf76d6e7c7f8688dc66757067ee4b19
