### ISSUE TITLE
sess.init() Error

### ISSUE THREAD

**Issue by TrumanShowlove** [tokenika/eosfactory#6]
>>> sess.init()
ERROR!
connect: Connection refused

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/truman/eosfactory/pyteos/sess.py", line 34, in init
    wallet = pyteos.Wallet(is_verbose=False)
  File "/home/truman/eosfactory/pyteos/pyteos.py", line 743, in __init__
    self.json["keys"] = []
TypeError: 'str' object does not support item assignment

**Comment by jakub-zarembinski** [comment]
Most probably your a victim of our mistake yesterday - we committed non-working code by mistake.

Please do a `git pull` and rebuild EOSFactory:
```
./build.sh -r
```
Let me know it helped.

**Comment by TrumanShowlove** [comment]
your website 404 ~not avaliable~

**Comment by jakub-zarembinski** [comment]
I'm not sure what you mean. Which website?

**Comment by TrumanShowlove** [comment]
ok,rebuild    solved the problem
thx
