### ISSUE TITLE
Testing multiple contracts in unison

### ISSUE THREAD

**Issue by ricktobacco** [tokenika/eosfactory#68]
how to write tests for eosfactory with two contracts deployed simultaneously (like if i am making calls in my contract against eosio.token)

my goal is to charge users eos for actions, i am using todd fleming's approach https://gist.github.com/tbfleming/d230f3ab2998e8858d3e51af7e4d9aeb

ultimately i want to continue from running on localhost to test this one jungle's eosio.token, how should i write my tests then?

thank you!
rick

**Comment by ricktobacco** [comment]
Also, I am very troubled by the error "deferred transaction with this payer and sender already exists". I understand why this is happening, although I don't think it should...I'm not allowed to trigger another deferred action by my contract before the first one finishes?

**Comment by stefanzarembinski** [comment]
I would like to answer your question accurately, hence, I need to have the problem better explained. 

Will you, please, specify the dataflow of the planned test?

Best regards.

SZ

**Comment by stefanzarembinski** [comment]
No news.
