### ISSUE TITLE
How to set permissions for call action in another contract with eosfactory?

### ISSUE THREAD

**Issue by golovin** [tokenika/eosfactory#83]
In case when contract B should call method from contract A (eosio.token) on behalf of active user we have to set eosio.code permission. Manually it can be done by this command
`cleos set account permission user1 active '{"threshold": 1,"keys": [{"key": "PRIVATE_KEY","weight": 1}],"accounts": [{"permission":{"actor":"contractB","permission":"eosio.code"},"weight":1}]}' owner -p user1`

How it can be done via eosfactory?

**Comment by jakub-zarembinski** [comment]
As of now, EOS Factory lacks this functionality.

However, we do consider it important for smart-contract testing and we'll aim to have it in the next release.

Thanks for the suggestion.

**Comment by golovin** [comment]
I can make PR with that functionality if needed

**Comment by jakub-zarembinski** [comment]
> I can make PR with that functionality if needed

That'd be great. Please do it against the `dev` branch.

**Comment by PopeyedLocket** [comment]
thank you so much golovin!

shouldn't "PRIVATE_KEY" be "PUBLIC_KEY" though?

Just going off of what
cleos set account permission -h
says.

**Comment by stefanzarembinski** [comment]
Done, will be effective in the next edition

**Comment by jakub-zarembinski** [comment]
@golovin 
Permissions should be working in the current release.
Please refer to these docs:
http://eosfactory.io/build/html/patterns/set/set_account_permission.html
http://eosfactory.io/build/html/patterns/set/set_action_permission.html
