### ISSUE TITLE
MAKE building teos_lib has exited with the above error

### ISSUE THREAD

**Issue by plouto5** [tokenika/eosfactory#9]
Im getting this installing on Ubuntu 18.04 Desktop.

home/dev/eosfactory/teos_lib/eos_interface.cpp:409:26: error: no viable conversion from
      'const eosio::chain::abi_def' to 'bytes' (aka 'vector<char>')
            .abi       = abi
                         ^~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_vector.h:326:7: note: 
      candidate constructor not viable: no known conversion from 'const eosio::chain::abi_def' to
      'const std::vector<char, std::allocator<char> > &' for 1st argument
      vector(const vector& __x)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_vector.h:344:7: note: 
      candidate constructor not viable: no known conversion from 'const eosio::chain::abi_def' to
      'std::vector<char, std::allocator<char> > &&' for 1st argument
      vector(vector&& __x) noexcept
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_vector.h:383:7: note: 
      candidate constructor not viable: no known conversion from 'const eosio::chain::abi_def' to
      'initializer_list<value_type>' (aka 'initializer_list<char>') for 1st argument
      vector(initializer_list<value_type> __l,
      ^
1 error generated.
CMakeFiles/teoslib.dir/build.make:110: recipe for target 'CMakeFiles/teoslib.dir/eos_interface.cpp.o' failed
make[2]: *** [CMakeFiles/teoslib.dir/eos_interface.cpp.o] Error 1
make[2]: Leaving directory '/home/dev/eosfactory/teos_lib/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/teoslib.dir/all' failed
make[1]: *** [CMakeFiles/teoslib.dir/all] Error 2
make[1]: Leaving directory '/home/dev/eosfactory/teos_lib/build'
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Thanks for any help with this and looking forward to amazing things with eosfactory!

**Comment by igavva** [comment]
Hi! Same here
/mnt/h/mnt/eosfactory/teos_lib/eos_interface.cpp:409:26: error: no viable conversion from 'const eosio::chain::abi_def'
      to 'bytes' (aka 'vector<char>')
            .abi       = abi
                         ^~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_vector.h:318:7: note: candidate
      constructor not viable: no known conversion from 'const eosio::chain::abi_def' to 'const std::vector<char,
      std::allocator<char> > &' for 1st argument
      vector(const vector& __x)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_vector.h:335:7: note: candidate
      constructor not viable: no known conversion from 'const eosio::chain::abi_def' to 'std::vector<char,
      std::allocator<char> > &&' for 1st argument
      vector(vector&& __x) noexcept
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_vector.h:373:7: note: candidate
      constructor not viable: no known conversion from 'const eosio::chain::abi_def' to 'initializer_list<value_type>'
      (aka 'initializer_list<char>') for 1st argument
      vector(initializer_list<value_type> __l,
      ^
1 error generated.
CMakeFiles/teoslib.dir/build.make:110: recipe for target 'CMakeFiles/teoslib.dir/eos_interface.cpp.o' failed
make[2]: *** [CMakeFiles/teoslib.dir/eos_interface.cpp.o] Error 1
make[2]: Leaving directory '/mnt/h/mnt/eosfactory/teos_lib/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/teoslib.dir/all' failed
make[1]: *** [CMakeFiles/teoslib.dir/all] Error 2
make[1]: Leaving directory '/mnt/h/mnt/eosfactory/teos_lib/build'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by igavva** [comment]
DAWN 4.0.0 is OK!

**Comment by jakub-zarembinski** [comment]
OK, so can I assume it's a matter of incompatibility with DAWN 4.1?

If so, the good news is that in a couple of days we'll be publishing a new release which will be compatible with 4.1

**Comment by plouto5** [comment]
Awesome looking forward to it!
